# easy copy paste characters:
#   ❯                    


format = """$directory $character"""  # left hand part
right_format = """$cmd_duration $all"""  # right hand part. ($all is all the other things)

continuation_prompt = "[ ](none)"

[cmd_duration]
format = "[took $duration]($style)"
style = "bright-black"

[character]
success_symbol = "[❯](green)"


[directory]
format = "[ ](yellow)[$path]($style)[$read_only]($read_only_style)"
style = "none"

[git_branch]
style = "none"
format = "[$symbol](red) [$branch]($style)"
symbol = ""

[git_status]
style = "none"
format = '[ $all_status ](bright-blue)[\[ $ahead_behind\]](dimmed) '
ahead = "+${count}"
diverged = "+$ahead_count-$behind_count"
behind = "-${count}"
up_to_date = "[](bright-green)"

deleted = "-"
untracked = "%%"
modified="*"
staged = "+"
renamed = "~"

[package]
format = "[$symbol$version]($style) "

[nodejs]
symbol=" "

[python]
format = '[ $symbol](blue)[$virtualenv]($style) [\($version\)](dimmed)'
style = 'none'
symbol = ' '
