# 
# ❯

# A minimal left prompt
format = """$directory $character"""

# move the rest of the prompt to the right
right_format = """$cmd_duration $all"""
continuation_prompt = "[ ](none)"

[cmd_duration]
format = "[$duration]($style)"
style = "bright-black"

[character]
success_symbol = "[❯](green)"


[directory]
format = "[ ](yellow)[$path]($style)[$read_only]($read_only_style)"
style = "none"

[git_branch]
style = "none"
format = "[$symbol](red) [$branch]($style)"
symbol = ""

[git_status]
style = "none"
format = '\[ [$all_status](green dimmed) [ $ahead_behind](red dimmed)\] '
ahead = "+${count}"
diverged = "+$ahead_count-$behind_count"
behind = "-${count}"
up_to_date = "[](green)"

deleted = "-"
untracked = "%%"
modified="*"
staged = "+"
renamed = "~"
stashed = "$"
clear = "[](green)"


[package]
format = "[$symbol$version]($style) [❯]($style) "

[nodejs]
symbol=" "

[python]
format = '[ $symbol](blue)[$virtualenv]($style) [\($version\)](blue dimmed)'
style = 'none'
symbol = ' '
