-- local lspkind_symbol_map = {
-- 	Class = "ﴯ",
-- 	Color = "",
-- 	Constant = "",
-- 	Constructor = "",
-- 	Enum = "",
-- 	EnumMember = "",
-- 	Event = "",
-- 	Field = "ﰠ",
-- 	File = "",
-- 	Folder = "",
-- 	Function = "",
-- 	Interface = "",
-- 	Keyword = "",
-- 	Method = "",
-- 	Module = "",
-- 	Operator = "",
-- 	Property = "ﰠ",
-- 	Reference = "",
-- 	Snippet = "",
-- 	Struct = "פּ",
-- 	Text = "",
-- 	TypeParameter = "",
-- 	Unit = "塞",
-- 	Value = "",
-- 	Variable = "",
-- }

vim.g.symbols_outline = {
	-- highlight_hovered_item = true,
	-- show_guides = true,
	auto_preview = false,
	-- position = 'right',
	-- relative_width = true,
	width = 33,
	auto_close = false,
	-- show_numbers = false,
	-- show_relative_numbers = false,
	-- show_symbol_details = true,
	-- preview_bg_highligTt = 'Pmenu',
	keymaps = { -- These keymaps can be a string or a table for multiple keys
		close = { "q" },
		--     goto_location = "<CR>",
		focus_location = { "o", "." },
		--     hover_symbol = "<C-space>",
		--     toggle_preview = "K",
		--     rename_symbol = "r",
		--     code_actions = "a",
	},
	-- lsp_blacklist = {},
	-- symbol_blacklist = {},
	symbols = {
		Array = { icon = "", hl = "TSConstant" },
		Boolean = { icon = "⏼", hl = "TSBoolean" },
		Class = { icon = "ﴯ", hl = "TSType" },
		Constant = { icon = "", hl = "TSConstant" },
		Constructor = { icon = "華", hl = "TSConstructor" },
		Enum = { icon = "", hl = "TSType" },
		EnumMember = { icon = "", hl = "TSField" },
		Event = { icon = "", hl = "TSType" },
		Field = { icon = "ﰠ", hl = "TSField" },
		File = { icon = "", hl = "TSURI" },
		Function = { icon = "", hl = "TSFunction" },
		Interface = { icon = "", hl = "TSType" },
		Key = { icon = "", hl = "TSType" },
		Method = { icon = "", hl = "TSMethod" },
		Module = { icon = "", hl = "TSNamespace" },
		Namespace = { icon = "", hl = "TSNamespace" },
		Null = { icon = "ﳠ", hl = "TSType" },
		Number = { icon = "", hl = "TSNumber" },
		Object = { icon = "⦿", hl = "TSType" },
		Operator = { icon = "+", hl = "TSOperator" },
		Package = { icon = "", hl = "TSNamespace" },
		Property = { icon = "", hl = "TSMethod" },
		String = { icon = "", hl = "TSString" },
		Struct = { icon = "פּ", hl = "TSType" },
		TypeParameter = { icon = "𝙏 ", hl = "TSParameter" },
		Variable = { icon = "", hl = "TSConstant" },
	},
}
