-- local actions = require("telescope.actions")

-- require("telescope").setup({
-- 	defaults = {
--         path_display = "",
-- 		sorting_strategy = "ascending",
-- 		mappings = {
-- 			i = {
-- 				["<C-j>"] = actions.move_selection_next,
-- 				["<C-k>"] = actions.move_selection_previous,
-- 			},
-- 		},
-- 		layout_config = {
-- 			horizontal = {
-- 				prompt_position = "top",
-- 			},
-- 		},
-- 	},
-- 	extensions = {
-- 		fzf = {
-- 			fuzzy = true,
-- 			override_generic_sorter = true,
-- 			override_file_sorter = true,
-- 			case_mode = "smart_case", -- or "ignore_case" or "respect_case"
-- 		},
-- 	},
-- })

-- require("telescope").load_extension("fzf")
